name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest,busybox:stable-glibc'

jobs:
  pull_and_package:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5  # 【修改】从 v4 升级到 v5 以适配 Node.js 24

    - name: Clean up Docker to free space
      run: |
        docker system prune -a -f
        docker volume prune -f

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}" --platform "linux/amd64"
          image_name="${image//\//_}"
          image_name="${image_name//:/_}"
          docker save "${image}" -o "${image_name}-amd64.tar"
          gzip -c "${image_name}-amd64.tar" > "${image_name}-amd64.tar.gz"
          rm "${image_name}-amd64.tar"
        done

    - name: Upload artifact
      uses: actions/upload-artifact@v5  # 【修改】从 v4 升级到 v5 以适配 Node.js 24
      with:
        name: my-artifact
        path: ${{ github.workspace }}/*.tar.gz
        retention-days: 1
